let SQL,db,currentRows=[],modalKind='';
const seed=[['1','credit','salary',93000,'HDFC','2026-07-20',''],['2','debit','household',25000,'ICICI-Namita','2026-07-20',''],['3','debit','SIP',5000,'ICICI','2026-07-20',''],['4','debit','Credit card',25000,'SBI','2026-07-20',''],['5','credit','Govt Arrear',6000,'SBI','2026-07-20',''],['6','debit','New iPhone',5000,'Kotak','2026-07-20',''],['7','debit','term plan',2500,'HDFC','2026-07-20','']];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n||0);
function q(sql,p=[]){const st=db.prepare(sql);st.bind(p);let a=[];while(st.step())a.push(st.getAsObject());st.free();return a}
function run(sql,p=[]){db.run(sql,p);save()}; function save(){localStorage.setItem('ledger-local-db',JSON.stringify(Array.from(db.export())))}
function guid(){return crypto.randomUUID?crypto.randomUUID():(Date.now()+'-'+Math.random().toString(16).slice(2))}
function toast(t){$('#toast').text(t).addClass('show');setTimeout(()=>$('#toast').removeClass('show'),2300)}
function initSchema(){db.run(`CREATE TABLE IF NOT EXISTS entries(guid TEXT PRIMARY KEY,entry TEXT NOT NULL CHECK(entry IN('credit','debit')),category TEXT NOT NULL,amount REAL NOT NULL CHECK(amount>0),source TEXT NOT NULL,date TEXT NOT NULL,remark TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS options(kind TEXT NOT NULL,name TEXT NOT NULL COLLATE NOCASE,PRIMARY KEY(kind,name));`);if(!q('SELECT guid FROM entries LIMIT 1').length){seed.forEach(x=>db.run('INSERT INTO entries VALUES(?,?,?,?,?,?,?)',x));['salary','household','SIP','Credit card','Govt Arrear','New iPhone','term plan'].forEach(x=>db.run('INSERT INTO options VALUES(?,?)',['category',x]));['HDFC','ICICI-Namita','ICICI','SBI','Kotak'].forEach(x=>db.run('INSERT INTO options VALUES(?,?)',['source',x]));save()}}
function options(kind){return q('SELECT name FROM options WHERE kind=? ORDER BY name',[kind]).map(x=>x.name)}
function refreshOptions(){['category','source'].forEach(k=>{let old=$('#'+k).val();$('#'+k).html('<option value="" disabled selected>Select '+k+'</option>'+options(k).map(x=>`<option>${esc(x)}</option>`).join('')).val(old);});$('#reportCategory').html('<option value="">All categories</option>'+options('category').map(x=>`<option>${esc(x)}</option>`).join(''));renderManage()}
function renderManage(){['category','source'].forEach(k=>$('#'+k+'List').html(options(k).map(x=>`<span class="chip">${esc(x)}<button class="remove-option" data-kind="${k}" data-name="${esc(x)}" title="Remove">×</button></span>`).join('')||'<span class="muted">None yet</span>'))}
function rowsHtml(rows){return rows.length?rows.map(r=>`<tr><td>${esc(r.date)}</td><td><span class="badge ${r.entry}">${r.entry}</span></td><td>${esc(r.category)}</td><td>${esc(r.source)}</td><td>${esc(r.remark||'—')}</td><td class="number amount-${r.entry}">${r.entry==='credit'?'+':'-'}${money(r.amount)}</td><td><button class="row-action delete-entry" data-id="${esc(r.guid)}">Delete</button></td></tr>`).join(''):'<tr><td colspan="7" style="text-align:center;color:#667085;padding:28px">No transactions found.</td></tr>'}
function recent(){let r=q('SELECT * FROM entries ORDER BY date DESC,rowid DESC LIMIT 10');$('#recentRows').html(rowsHtml(r));$('#recentCount').text(`${q('SELECT COUNT(*) n FROM entries')[0].n} total transactions · latest 10 shown`)}
function report(){let f={from:$('#fromDate').val(),to:$('#toDate').val(),type:$('#reportType').val(),cat:$('#reportCategory').val(),remark:$('#remarkSearch').val().trim()};let wh=[],p=[];if(f.from){wh.push('date>=?');p.push(f.from)}if(f.to){wh.push('date<=?');p.push(f.to)}if(f.type){wh.push('entry=?');p.push(f.type)}if(f.cat){wh.push('category=?');p.push(f.cat)}if(f.remark){wh.push('remark LIKE ?');p.push('%'+f.remark+'%')}let where=wh.length?' WHERE '+wh.join(' AND '):'';currentRows=q('SELECT * FROM entries'+where+' ORDER BY date DESC,rowid DESC',p);let totals=q(`SELECT COALESCE(SUM(CASE WHEN entry='credit' THEN amount END),0) credit,COALESCE(SUM(CASE WHEN entry='debit' THEN amount END),0) debit,COUNT(*) n FROM entries${where}`,p)[0];$('#totalCredit').text(money(totals.credit));$('#totalDebit').text(money(totals.debit));$('#netBalance').text(money(totals.credit-totals.debit));$('#recordCount').text(totals.n);$('#reportRows').html(rowsHtml(currentRows));$('#reportDescription').text(currentRows.length+' transaction'+(currentRows.length===1?'':'s')+' matching current filters.');let by=q(`SELECT category,COALESCE(SUM(CASE WHEN entry='credit' THEN amount END),0) credit,COALESCE(SUM(CASE WHEN entry='debit' THEN amount END),0) debit FROM entries${where} GROUP BY category ORDER BY (credit+debit) DESC`,p);$('#categoryRows').html(by.length?by.map(x=>`<tr><td>${esc(x.category)}</td><td class="amount-credit">${money(x.credit)}</td><td class="amount-debit">${money(x.debit)}</td><td>${money(x.credit-x.debit)}</td></tr>`).join(''):'<tr><td colspan="4" style="text-align:center;padding:25px">No category totals.</td></tr>')}
function csv(rows,name){let text=['GUID,Type,Category,Amount,Source,Date,Remark',...rows.map(r=>[r.guid,r.entry,r.category,r.amount,r.source,r.date,r.remark].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$(async function(){try{SQL=await initSqlJs({locateFile:f=>f});let saved=localStorage.getItem('ledger-local-db');db=saved?new SQL.Database(new Uint8Array(JSON.parse(saved))):new SQL.Database();initSchema();$('#dbStatus').text('Offline database ready');$('#entryDate').val(new Date().toISOString().slice(0,10));refreshOptions();recent();report()}catch(e){$('#dbStatus').text('Database error');alert('Could not start SQLite: '+e.message)} $('#year').text(new Date().getFullYear());
$('.nav').on('click',function(){$('.nav,.view').removeClass('active');$(this).addClass('active');$('#'+$(this).data('view')).addClass('active')});
$('#entryForm').on('submit',function(e){e.preventDefault();let x={guid:$('#entryGuid').val()||guid(),entry:$('#entryType').val(),category:$('#category').val(),amount:+$('#amount').val(),source:$('#source').val(),date:$('#entryDate').val(),remark:$('#remark').val().trim()};if(!x.category||!x.source)return toast('Select a category and source.');run('INSERT INTO entries VALUES(?,?,?,?,?,?,?)',[x.guid,x.entry,x.category,x.amount,x.source,x.date,x.remark]);toast('Entry saved');this.reset();$('#entryDate').val(new Date().toISOString().slice(0,10));refreshOptions();recent();report()});
$('.add-option').on('click',function(){modalKind=$(this).data('kind');$('#modalTitle').text('Add '+modalKind);$('#modalInput').val('');$('#modal').prop('hidden',false);$('#modalInput').trigger('focus')});$('#closeModal').on('click',()=>$('#modal').prop('hidden',true));$('#modalForm').on('submit',function(e){e.preventDefault();let name=$('#modalInput').val().trim();try{run('INSERT INTO options VALUES(?,?)',[modalKind,name]);refreshOptions();$('#'+modalKind).val(name);toast('Added '+name);$('#modal').prop('hidden',true)}catch(e){toast('That '+modalKind+' already exists.')}});$('.simple-add').on('submit',function(e){e.preventDefault();let k=$(this).data('kind'),n=$(this).find('input').val().trim();try{run('INSERT INTO options VALUES(?,?)',[k,n]);this.reset();refreshOptions();toast('Added '+n)}catch(e){toast('Already exists.')}});$(document).on('click','.remove-option',function(){let k=$(this).data('kind'),n=$(this).data('name');if(q('SELECT COUNT(*) n FROM entries WHERE '+k+'=?',[n])[0].n)return toast('Cannot remove an option used by an entry.');run('DELETE FROM options WHERE kind=? AND name=?',[k,n]);refreshOptions();toast('Removed '+n)}).on('click','.delete-entry',function(){if(confirm('Delete this transaction?')){run('DELETE FROM entries WHERE guid=?',[$(this).data('id')]);recent();report();toast('Entry deleted')}});
$('#reportForm').on('submit',e=>{e.preventDefault();report()});$('#clearReport').on('click',()=>{$('#reportForm')[0].reset();report()});$('#csvAll').on('click',()=>csv(q('SELECT * FROM entries ORDER BY date DESC'),'ledger-all.csv'));$('#csvReport').on('click',()=>csv(currentRows,'ledger-report.csv'));$('#exportDb').on('click',()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([db.export()],{type:'application/x-sqlite3'}));a.download='ledger-local-backup.db';a.click();URL.revokeObjectURL(a.href)});$('#importDb').on('change',function(){let file=this.files[0];if(!file)return;let reader=new FileReader;reader.onload=e=>{try{let next=new SQL.Database(new Uint8Array(e.target.result));next.exec('SELECT * FROM entries LIMIT 1');db=next;save();refreshOptions();recent();report();toast('Backup imported')}catch(err){toast('That is not a valid Ledger Local backup.')}};reader.readAsArrayBuffer(file)});$('#resetData').on('click',()=>{if(confirm('Permanently erase all transactions and options from this browser?')){localStorage.removeItem('ledger-local-db');location.reload()}});});